<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../ExposePinGenerationRequestService.wsdl"/>
      <rootElement name="pingenrequest" namespace="http://www.example.org"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../PinGenRequestBPEL.wsdl"/>
      <rootElement name="pingenrequest" namespace="http://www.example.org"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.5.0(build 110418.1550.0174) AT [FRI JAN 13 08:15:07 SAST 2012]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:inp1="http://www.example.org"
                xmlns:tns="http://oracle.com/sca/soapservice/PinGenerationSOA/PinGenerationProject/ExposePinGenerationRequestService"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:client="http://xmlns.oracle.com/PinGenerationSOA/PinGenerationProject/PinGenRequestBPEL"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl inp1 tns xsd wsdl plnk client bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref bpmn ora socket ldap">
  <xsl:template match="/">
    <inp1:pingenrequest>
      <inp1:dealerid>
        <xsl:value-of select="/inp1:pingenrequest/inp1:dealerid"/>
      </inp1:dealerid>
      <inp1:ordernumber>
        <xsl:value-of select="/inp1:pingenrequest/inp1:ordernumber"/>
      </inp1:ordernumber>
      <inp1:templatenumber>
        <xsl:value-of select="/inp1:pingenrequest/inp1:templatenumber"/>
      </inp1:templatenumber>
      <inp1:numberofpins>
        <xsl:value-of select="/inp1:pingenrequest/inp1:numberofpins"/>
      </inp1:numberofpins>
      <inp1:voucherexporttype>
        <xsl:value-of select="/inp1:pingenrequest/inp1:voucherexporttype"/>
      </inp1:voucherexporttype>
      <inp1:processdate>
        <xsl:value-of select="/inp1:pingenrequest/inp1:processdate"/>
      </inp1:processdate>
      <inp1:customerordernumber>
        <xsl:value-of select="/inp1:pingenrequest/inp1:customerordernumber"/>
      </inp1:customerordernumber>
      <inp1:approved>
        <xsl:value-of select="/inp1:pingenrequest/inp1:approved"/>
      </inp1:approved>
    </inp1:pingenrequest>
  </xsl:template>
</xsl:stylesheet>
