<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://sample.thegreyhope.co.za/" 
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	name="ProxyService"
	targetNamespace="http://sample.thegreyhope.co.za/" >
	
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://sample.thegreyhope.co.za/"
				schemaLocation="XMLSchema_-1147695334.xsd" />
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="approveOrder">
		<wsdl:part name="parameters" element="tns:approveOrder" />
	</wsdl:message>
	<wsdl:message name="approveOrderResponse">
		<wsdl:part name="parameters" element="tns:approveOrderResponse" />
	</wsdl:message>
	
	<wsdl:portType name="ProxyService">
		<wsdl:operation name="approveOrder">
			<wsdl:input message="tns:approveOrder" />
			<wsdl:output message="tns:approveOrderResponse" />
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="ProxyServiceSOAP" type="tns:ProxyService">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="approveOrder">
			<soap:operation soapAction="http://www.example.org/ProxyService/approveTheOrder" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	
	<wsdl:service name="ProxyService">
		<wsdl:port binding="tns:ProxyServiceSOAP" name="ProxyServiceSOAP">
			<soap:address location="http://www.example.org/" />
		</wsdl:port>
	</wsdl:service>
	
</wsdl:definitions>
